FakeServiceProvider/Controllers/SamlController.cs
using ComponentSpace.Saml2;
using ComponentSpace.Saml2.Metadata.Export;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FakeServiceProvider.Controllers
{
    [Route("[controller]/[action]")]
    public class SamlController : Controller
    {

        #region Member Variables
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IConfiguration _configuration;
        private readonly IConfigurationToMetadata _configurationToMetadata;
        private readonly ISamlServiceProvider _samlServiceProvider;
        private readonly SignInManager<IdentityUser> _signInManager;
        #endregion

        #region Constructor
        public SamlController(
            IConfiguration configuration,
            IConfigurationToMetadata configurationToMetadata,
            ISamlServiceProvider samlServiceProvider,
            SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager)
        {
            _configuration = configuration;
            _configurationToMetadata = configurationToMetadata;
            _samlServiceProvider = samlServiceProvider;
            _signInManager = signInManager;
            _userManager = userManager;

        }
        #endregion

        public async Task<IActionResult> AssertionConsumerService()
        {
            var ssoResult = await _samlServiceProvider.ReceiveSsoAsync();

            var user = await _userManager.FindByNameAsync(ssoResult.UserID);

            if (user == null)
            {
                user = new IdentityUser { UserName = ssoResult.UserID, Email = ssoResult.UserID };
                var result = await _userManager.CreateAsync(user);

                if (!result.Succeeded)
                {
                    throw new Exception($"The user {ssoResult.UserID} couldn't be created - {result}");
                }

            }

            await _signInManager.SignInAsync(user, isPersistent: false);
            bool flag = _signInManager.IsSignedIn(User);

            if (!string.IsNullOrEmpty(ssoResult.RelayState))
            {
                return LocalRedirect(ssoResult.RelayState);

            }

            return LocalRedirect("/index");
        }

        public async Task<IActionResult> InitiateSingleSignOn(string returnUrl = null)
        {
            var partnerName = _configuration["PartnerName"];

            // request sent to IdP's SSO Service
            await _samlServiceProvider.InitiateSsoAsync(partnerName, returnUrl);

            return new EmptyResult();
        }

        public async Task<IActionResult> InitiatedSingleLogout(string returnUrl = "/Logout")
        {
            var partnerName = _configuration["PartnerName"];

            // send logout request to Idp's SLO service
            await _samlServiceProvider.InitiateSloAsync(relayState: returnUrl);
            return new EmptyResult();
        }

        public async Task<IActionResult> SingleLogoutService()
        {
            // SP receive logout request from IdP
            var sloResult = await _samlServiceProvider.ReceiveSloAsync();

            if (sloResult.IsResponse)
            {
                // SP-initated SLO
                //if (sloResult.HasCompleted)
                //{
                    await _signInManager.SignOutAsync();
                    if (!string.IsNullOrEmpty(sloResult.RelayState))
                    {
                        return LocalRedirect(sloResult.RelayState);
                    }
                    return RedirectToPage("/Index");
                //}
            }
            else
            {
                // idp-initiated SLO
                await _signInManager.SignOutAsync();

                // send back response to IdP's SLO service
                await _samlServiceProvider.SendSloAsync();
            }

            return new EmptyResult();

        }


    }
}

FakeServiceProvider/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FakeServiceProvider.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FakeServiceProvider/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FakeServiceProvider.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly SignInManager<IdentityUser> _signInManager;

        public IndexModel(ILogger<IndexModel> logger, SignInManager<IdentityUser> signInManager)
        {
            _logger = logger;
            _signInManager = signInManager;
        }

        public void OnGet()
        {
            bool flag = _signInManager.IsSignedIn(User);
           
        }
    }
}

FakeServiceProvider/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FakeServiceProvider.Pages
{
    public class LogoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

FakeServiceProvider/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FakeServiceProvider.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

FakeServiceProvider/Pages/welcome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FakeServiceProvider.Pages
{
    public class welcomeModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

FakeServiceProvider/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> UserManager

@if (signInManager.IsSignedIn(User))
{
    <div class="text-center">
        <h1 class="display-4">Welcome to Service Provider + @User.Identity.Name</h1>
        <a asp-controller="Saml" asp-action="InitiatedSingleLogout" class="btn btn-primary btn-dark">Log out</a>
    </div>
}
else
{
    <div class="text-center">
        <h1 class="display-4">Welcome to Service Provider</h1>
        <p>
            <a asp-controller="Saml" asp-action="InitiateSingleSignOn" class="btn btn-primary btn-dark">Login through SSO</a>
        </p>
    </div>
}



FakeServiceProvider/Pages/Logout.cshtml
@page
@model FakeServiceProvider.Pages.LogoutModel
@{
}

    <header>
        <h1>@ViewData["Title"]</h1>
        <p>You have successfully logged out of the application.</p>
        <a asp-page="/Index">Back to Main Page</a>
    </header>

FakeServiceProvider/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Service Provider</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Service Provider</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Service Provider - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

FakeServiceProvider/Pages/welcome.cshtml
@page
@model FakeServiceProvider.Pages.welcomeModel
@{
}

@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
@inject UserManager<IdentityUser> UserManager

@if (signInManager.IsSignedIn(User))
{
    <div class="text-center">
        <h1 class="display-4">Welcome to Service Provider... + @User.Identity.Name</h1>
        <a asp-page="/Index">Back to Main Page</a>
    </div>
}
else
{
    <div class="text-center">
        <h1 class="display-4">Welcome to Service Provider</h1>
        <a asp-page="/Index">Back to Main Page</a>
    </div>
}